# SciKitLearn DecisionTreeClassifier (based on CART)

### 1) Loading the digits dataset from the datasets provided in SciKitLearn. 

In [156]:
from sklearn import datasets
digits = datasets.load_digits()
# Features
x = digits.data
# Labels
y = digits.target
# images
images = digits.images

In [158]:
import numpy as np
import pandas as pd
digits.keys()


".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixel

In [85]:
data = np.array([('y', 's', 'r'), ('y', 's', 'r'), ('g', 's', 'i'), ('g', 'l', 'i'), ('y', 'l', 'r'), ('y', 's', 'r'), ('y', 's', 'r'), ('y', 's', 'r'), ('g', 's', 'r'), ('y', 'l', 'r'), ('y', 'l', 'r'), ('y', 'l', 'r'), ('y', 'l', 'r'), ('y', 'l', 'r'), ('y', 's', 'i'), ('y', 'l', 'i')])
attributes = dict([('color', ['y', 'g', 'b']), ('size', ['s', 'l']), ('shape', ['r', 'i'])])
target = np.array(['+', '-', '+', '-', '+', '+', '+', '+', '-', '-', '+', '-', '-', '-', '+', '+']) 

In [87]:
attributes['color']
data

array([['y', 's', 'r'],
       ['y', 's', 'r'],
       ['g', 's', 'i'],
       ['g', 'l', 'i'],
       ['y', 'l', 'r'],
       ['y', 's', 'r'],
       ['y', 's', 'r'],
       ['y', 's', 'r'],
       ['g', 's', 'r'],
       ['y', 'l', 'r'],
       ['y', 'l', 'r'],
       ['y', 'l', 'r'],
       ['y', 'l', 'r'],
       ['y', 'l', 'r'],
       ['y', 's', 'i'],
       ['y', 'l', 'i']], dtype='<U1')

In [200]:
data = np.array([[1, 6, 12],
                [5, 3, 8],
                 [5, 3, 11],
                [10, 6, 0]])
e = np.array(data, dtype='<U21')

In [201]:
e

array([['1', '6', '12'],
       ['5', '3', '8'],
       ['5', '3', '11'],
       ['10', '6', '0']], dtype='<U21')

In [151]:
datas = {}
targets = {}
# idx = 0
# for values in ['y', 'g', 'b']:
# idx = 1
# for values in ['s', 'l']:  
idx = 2
for values in ['r', 'i']:
    targets[values] = target[values == data[:, idx]]
    datas[values] = data[values == data[:, idx]]
    datas[values] = np.delete(data[values == data[:, idx]], 2, 1)
    print(len(targets[values]))
#     if len(targets[values]) != 0:
#         datas[values] = np.delete(data[values == data[:, idx]], 0, idx)
#     else:
#         datas[values] = data[values == data[:, idx]]
    
datas

12
4


{'r': array([['y', 's'],
        ['y', 's'],
        ['y', 'l'],
        ['y', 's'],
        ['y', 's'],
        ['y', 's'],
        ['g', 's'],
        ['y', 'l'],
        ['y', 'l'],
        ['y', 'l'],
        ['y', 'l'],
        ['y', 'l']], dtype='<U1'), 'i': array([['g', 's'],
        ['g', 'l'],
        ['y', 's'],
        ['y', 'l']], dtype='<U1')}

In [118]:
import collections
d = collections.OrderedDict()
# d['a'] = 2
# d['b'] = 1
# d['c'] = 5
# d['d'] = 6
# for key in d.keys():
#     print(key)
if (not d):
    print("hello")


hello


In [92]:
datas = {}
targets = {}
for values in attributes['size']:
    datas[values] = data[values == data[:, 1]]
    targets[values] = target[values == data[:, 1]]
targets

{'s': array(['+', '-', '+', '+', '+', '+', '-', '+'], dtype='<U1'),
 'l': array(['-', '+', '-', '+', '-', '-', '-', '+'], dtype='<U1')}

In [20]:
# convert array of int target names to array of str
import numpy as np
t = digits.target_names
target_names=np.array(t).astype('str').tolist()

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

### 2) Spliting the data set into 70% training data and 30% test data.

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, img_tr, img_ts = train_test_split(x, y, images, test_size=0.3)

In [167]:
att = {}
x_train[1, 9]
for i in range(1200):
    for j in range(64):
        if x_train[i,j] not in att:
            att[x_train[i,j]] = 1
        else:
            att[x_train[i,j]] += 1
att

{0.0: 37518,
 4.0: 2147,
 12.0: 2460,
 16.0: 6945,
 8.0: 2337,
 15.0: 2874,
 1.0: 2774,
 14.0: 2420,
 7.0: 1764,
 6.0: 1672,
 10.0: 1819,
 13.0: 2397,
 2.0: 2197,
 3.0: 1985,
 9.0: 1745,
 5.0: 1857,
 11.0: 1889}

### 3) Set up a DecisionTreeClassifier

In [27]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
# train a decision tree classifier for the digits dataset based on the training data
classifier = classifier.fit(x_train, y_train)

#### Produce a plot of the tree with GraphViz

In [28]:
import graphviz 
dot_data = tree.export_graphviz(classifier, out_file=None,   
                      class_names=target_names,  
                      filled=True, rounded=True,  
                      special_characters=True)  
graph = graphviz.Source(dot_data) 
graph.render("digits") 
# graph

'digits.pdf'

### 4) Test the classifier with the remaining test data

In [30]:
# predicting the labels of the test set
y_hat = classifier.predict(x_test)

In [31]:
# Evaluating the classifier
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96        63
           1       0.85      0.73      0.79        63
           2       0.87      0.88      0.87        51
           3       0.83      0.77      0.80        56
           4       0.90      0.96      0.93        49
           5       0.91      0.87      0.89        61
           6       0.91      0.93      0.92        55
           7       0.87      0.94      0.90        48
           8       0.66      0.69      0.67        48
           9       0.78      0.85      0.81        46

    accuracy                           0.86       540
   macro avg       0.85      0.86      0.85       540
weighted avg       0.86      0.86      0.86       540



In [32]:
print(confusion_matrix(y_test, y_hat))

[[61  0  1  0  0  1  0  0  0  0]
 [ 1 46  1  2  2  1  2  0  7  1]
 [ 0  2 45  1  0  0  1  0  0  2]
 [ 0  0  3 43  0  1  0  1  4  4]
 [ 0  0  0  0 47  1  0  1  0  0]
 [ 0  1  0  0  1 53  1  1  1  3]
 [ 0  1  1  0  0  0 51  0  2  0]
 [ 0  1  0  0  1  0  0 45  1  0]
 [ 2  3  1  4  1  0  1  2 33  1]
 [ 0  0  0  2  0  1  0  2  2 39]]


The **min_samples_split** parameter:
will evaluate the number of samples in the node, and 
if the number is less than the minimum the split will be avoided and the node will be a leaf.

The **min_samples_leaf** parameter checks before the node is generated, that is, 
if the possible split results in a child with fewer samples, the split will be avoided 
(since the minimum number of samples for the child to be a leaf has not been reached) 
and the node will be replaced by a leaf.

In all cases, when we have samples with more than one Class in a leaf, the Final Class will be the most likely to happen, according to the samples that reached it in training.

### 5) Tuning parameters

In [45]:
# importing libraries
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
X, y = x_train, y_train

# Creating a DecisionTreeClassifier
dec_tree = tree.DecisionTreeClassifier()
# Steps : training a Decision Tree Classifier on the data.
pipe = Pipeline(steps=[('dec_tree', dec_tree)])


# Creating lists of parameter for Decision Tree Classifier
splitter = ["best", "random"]
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12, None]
splits = [2, 5, 8, 10]
leaves = [1, 2, 3, 4, 5, 6]
# Creating a dictionary of all the parameter options 
# Note that we can access the parameters of steps of a pipeline by using '__’
parameters = dict(#pca__n_components=n_components,
                  dec_tree__splitter=splitter,
                  dec_tree__criterion=criterion,
                  dec_tree__min_samples_split=splits,
                  dec_tree__min_samples_leaf=leaves,
                  dec_tree__max_depth=max_depth)

# Creating a grid search object
clf_GS = GridSearchCV(pipe, parameters)

# Fitting the grid search
clf_GS.fit(X, y)

# Viewing The Best Parameters
print('Best splitter:', clf_GS.best_estimator_.get_params()['dec_tree__splitter'])
print('Best Criterion:', clf_GS.best_estimator_.get_params()['dec_tree__criterion'])
print('Best min_samples_split:', clf_GS.best_estimator_.get_params()['dec_tree__min_samples_split'])
print('Best min_samples_leaf:', clf_GS.best_estimator_.get_params()['dec_tree__min_samples_leaf'])
print('Best max_depth:', clf_GS.best_estimator_.get_params()['dec_tree__max_depth'])

/home/nabil/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best splitter: best
Best Criterion: entropy
Best min_samples_split: 2
Best min_samples_leaf: 1
Best max_depth: 8


/home/nabil/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


#### Change the parameters of the classifier

In [46]:
classifier = tree.DecisionTreeClassifier(splitter="best",
                                         criterion="entropy",
                                         min_samples_split=2,
                                         min_samples_leaf=1,
                                         max_depth=None)
# training
classifier = classifier.fit(x_train, y_train)

# predicting the labels of the test set
y_hat = classifier.predict(x_test)

# Evaluation
print(classification_report(y_test, y_hat))
print(confusion_matrix(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95        63
           1       0.87      0.86      0.86        63
           2       0.89      0.82      0.86        51
           3       0.89      0.75      0.82        56
           4       0.90      0.88      0.89        49
           5       0.93      0.92      0.93        61
           6       0.85      0.93      0.89        55
           7       0.91      0.88      0.89        48
           8       0.83      0.92      0.87        48
           9       0.81      0.91      0.86        46

    accuracy                           0.88       540
   macro avg       0.88      0.88      0.88       540
weighted avg       0.89      0.88      0.88       540

[[61  0  0  0  0  0  1  0  0  1]
 [ 0 54  2  1  1  2  0  1  0  2]
 [ 0  2 42  2  0  0  1  1  3  0]
 [ 1  2  1 42  0  0  4  1  2  3]
 [ 3  1  0  0 43  1  0  1  0  0]
 [ 0  0  0  0  0 56  1  0  0  4]
 [ 0  1  0  0  2  0 51  0  1  0]
 [ 0  1  1